# -*- coding: utf-8 -*-
"""M25CSA018_NLU_Ass2_Prob2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8ce94JRC18QzuJP_2UfPIeWW5WJdTzA
"""

# ============================================
# PROBLEM 2: CHARACTER-LEVEL NAME GENERATION USING RNN VARIANTS
# ============================================

# Install required packages
!pip install torch numpy matplotlib seaborn -q

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import random
import string
import warnings
import os

# Set random seeds
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

print("="*60)
print("PROBLEM 2: CHARACTER-LEVEL NAME GENERATION USING RNN VARIANTS")
print("="*60)

# ============================================
# DATASET GENERATION
# ============================================

class IndianNameDataset:
    """
    Generate comprehensive Indian names dataset with surnames
    """
    def __init__(self):
        # First names
        self.first_names = [
            "Aarav", "Vihaan", "Vivaan", "Ananya", "Diya", "Arjun", "Advik", "Kabir", "Reyansh", "Shaurya",
            "Aryan", "Ishaan", "Dhruv", "Krishna", "Shiv", "Rudra", "Yash", "Vedant", "Ayaan", "Rohan",
            "Siddharth", "Rahul", "Amit", "Raj", "Vikram", "Kunal", "Tarun", "Nikhil", "Ankit", "Manish",
            "Aanya", "Anaya", "Ishita", "Myra", "Saanvi", "Aditi", "Aaradhya", "Anika", "Avni", "Charvi",
            "Divya", "Ira", "Jiya", "Kavya", "Lakshmi", "Meera", "Naina", "Pooja", "Priya", "Riya",
            "Sakshi", "Tanvi", "Uma", "Vidya", "Yamini", "Neha", "Sneha", "Pallavi", "Swati", "Radha"
        ]

        # Surnames
        self.surnames = [
            "Sharma", "Verma", "Gupta", "Agarwal", "Singh", "Kumar", "Patel", "Reddy", "Rao", "Yadav",
            "Jha", "Mishra", "Tiwari", "Dubey", "Pandey", "Choudhary", "Thakur", "Rajput", "Khan", "Ansari",
            "Nair", "Menon", "Pillai", "Iyer", "Iyengar", "Naidu", "Shetty", "Hegde", "Gowda", "Desai",
            "Joshi", "Kulkarni", "Patil", "Pawar", "Shinde", "More", "Chavan", "Gaikwad", "Kadam", "Rajan",
            "Krishnan", "Narayanan", "Venkatesan", "Sundaram", "Anand", "Bharathi", "Chandran", "Easwaran",
            "Srivastava", "Trivedi", "Dwivedi", "Chaturvedi", "Shukla", "Upadhyay", "Bajpai", "Tiwari",
            "Sandhu", "Gill", "Brar", "Dhillon", "Sidhu", "Walia", "Chahal", "Bajwa", "Ali", "Siddiqui"
        ]

    def generate_names(self, num_names=1000):
        """Generate 1000 Indian names with surnames"""
        names = []

        # Generate combinations
        for i in range(num_names):
            first = random.choice(self.first_names)
            surname = random.choice(self.surnames)
            full_name = f"{first} {surname}"
            names.append(full_name)

        # Save to file
        with open('TrainingNames.txt', 'w', encoding='utf-8') as f:
            for name in names:
                f.write(name + '\n')

        print(f"\n{'='*50}")
        print(f"TASK 0: DATASET GENERATION")
        print(f"{'='*50}")
        print(f"✓ Generated {len(names)} Indian names with surnames")
        print(f"✓ Saved to 'TrainingNames.txt'")
        print(f"\nSample names:")
        for name in names[:15]:
            print(f"  • {name}")

        return names

# ============================================
# DATA PREPARATION - FIXED
# ============================================

class CharacterDataset(Dataset):
    """
    Dataset for character-level sequence modeling
    """
    def __init__(self, names, seq_length=20):
        # Collect all characters
        chars = set()
        for name in names:
            chars.update(name.lower())

        # Add special tokens
        self.chars = ['<START>', '<END>'] + sorted(list(chars))
        self.char_to_idx = {ch: i for i, ch in enumerate(self.chars)}
        self.idx_to_char = {i: ch for i, ch in enumerate(self.chars)}
        self.vocab_size = len(self.chars)
        self.seq_length = seq_length

        # Prepare sequences
        self.sequences = []
        self.targets = []

        for name in names:
            # Convert to lowercase
            name = name.lower()
            # Add start and end tokens
            seq = ['<START>'] + list(name) + ['<END>']

            # Create sequences
            for i in range(len(seq) - 1):
                # Get previous seq_length characters
                start_idx = max(0, i - seq_length + 1)
                input_seq = seq[start_idx:i+1]

                # Pad if needed
                while len(input_seq) < seq_length:
                    input_seq.insert(0, '<START>')

                target_char = seq[i+1]

                # Convert to indices
                input_indices = [self.char_to_idx[ch] for ch in input_seq]
                target_idx = self.char_to_idx[target_char]

                self.sequences.append(input_indices)
                self.targets.append(target_idx)

        print(f"\n{'='*50}")
        print(f"DATA PREPARATION")
        print(f"{'='*50}")
        print(f"✓ Total sequences created: {len(self.sequences)}")
        print(f"✓ Vocabulary size: {self.vocab_size}")
        print(f"✓ Sequence length: {seq_length}")
        print(f"✓ Characters: {', '.join(self.chars[:15])}...")

        # Verify we have data
        if len(self.sequences) == 0:
            raise ValueError("No sequences created! Check your data.")

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        return (torch.tensor(self.sequences[idx], dtype=torch.long),
                torch.tensor(self.targets[idx], dtype=torch.long))

# ============================================
# TASK-1: MODEL IMPLEMENTATION
# ============================================

class VanillaRNN(nn.Module):
    """Vanilla RNN for character-level name generation"""
    def __init__(self, vocab_size, hidden_size=128, num_layers=2, dropout=0.3):
        super(VanillaRNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.rnn = nn.RNN(hidden_size, hidden_size, num_layers,
                          batch_first=True, dropout=dropout if num_layers > 1 else 0)
        self.fc = nn.Linear(hidden_size, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, hidden):
        x = self.embedding(x)
        x = self.dropout(x)
        out, hidden = self.rnn(x, hidden)
        out = out[:, -1, :]
        out = self.fc(out)
        return out, hidden

    def init_hidden(self, batch_size):
        return torch.zeros(self.num_layers, batch_size, self.hidden_size)

class BidirectionalLSTM(nn.Module):
    """Bidirectional LSTM for character-level name generation"""
    def __init__(self, vocab_size, hidden_size=128, num_layers=2, dropout=0.3):
        super(BidirectionalLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.lstm = nn.LSTM(hidden_size, hidden_size, num_layers,
                            batch_first=True, bidirectional=True,
                            dropout=dropout if num_layers > 1 else 0)
        self.fc = nn.Linear(hidden_size * 2, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, hidden):
        x = self.embedding(x)
        x = self.dropout(x)
        out, hidden = self.lstm(x, hidden)
        out = out[:, -1, :]
        out = self.fc(out)
        return out, hidden

    def init_hidden(self, batch_size):
        h0 = torch.zeros(self.num_layers * 2, batch_size, self.hidden_size)
        c0 = torch.zeros(self.num_layers * 2, batch_size, self.hidden_size)
        return (h0, c0)

class AttentionRNN(nn.Module):
    """RNN with Basic Attention Mechanism"""
    def __init__(self, vocab_size, hidden_size=128, num_layers=2, dropout=0.3):
        super(AttentionRNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.rnn = nn.RNN(hidden_size, hidden_size, num_layers,
                          batch_first=True, dropout=dropout if num_layers > 1 else 0)
        self.attention = nn.Linear(hidden_size, 1)
        self.fc = nn.Linear(hidden_size, vocab_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, hidden):
        x = self.embedding(x)
        x = self.dropout(x)
        out, hidden = self.rnn(x, hidden)

        # Attention mechanism
        attention_weights = torch.softmax(self.attention(out), dim=1)
        context = torch.sum(attention_weights * out, dim=1)

        out = self.fc(context)
        return out, hidden

    def init_hidden(self, batch_size):
        return torch.zeros(self.num_layers, batch_size, self.hidden_size)

# ============================================
# TRAINING FUNCTION
# ============================================

class NameGenerator:
    """Train and evaluate name generation models"""
    def __init__(self, model, dataset, learning_rate=0.001, device='cpu'):
        self.model = model.to(device)
        self.dataset = dataset
        self.device = device
        self.criterion = nn.CrossEntropyLoss()
        self.optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    def train(self, epochs=15, batch_size=32):
        """Train the model"""
        dataloader = DataLoader(self.dataset, batch_size=batch_size, shuffle=True)
        losses = []

        print(f"\n{'='*50}")
        print(f"Training {self.model.__class__.__name__}")
        print(f"{'='*50}")
        total_params = sum(p.numel() for p in self.model.parameters())
        print(f"Trainable parameters: {total_params:,}")
        print(f"Hidden size: 128, Layers: 2, Learning rate: 0.001")

        for epoch in range(epochs):
            total_loss = 0
            for batch_idx, (data, target) in enumerate(dataloader):
                data, target = data.to(self.device), target.to(self.device)
                hidden = self.model.init_hidden(data.size(0))

                # Move hidden to device
                if isinstance(hidden, tuple):
                    hidden = (hidden[0].to(self.device), hidden[1].to(self.device))
                else:
                    hidden = hidden.to(self.device)

                self.optimizer.zero_grad()
                output, hidden = self.model(data, hidden)
                loss = self.criterion(output, target)
                loss.backward()

                # Gradient clipping
                torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)

                self.optimizer.step()
                total_loss += loss.item()

            avg_loss = total_loss / len(dataloader)
            losses.append(avg_loss)

            if (epoch + 1) % 10 == 0:
                print(f"  Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}")

        return losses

    def generate_name(self, max_length=25, temperature=0.5):
        """Generate a name with surname - FIXED"""
        self.model.eval()

        # Start with a random character
        start_char = random.choice(['a', 'r', 's', 'm', 'k', 'p', 'v', 'n', 'd', 'g'])

        # Use list for characters
        name_chars = [start_char]
        hidden = self.model.init_hidden(1)

        if isinstance(hidden, tuple):
            hidden = (hidden[0].to(self.device), hidden[1].to(self.device))
        else:
            hidden = hidden.to(self.device)

        space_added = False

        for step in range(max_length):
            # Prepare input sequence
            seq = []
            for ch in name_chars[-self.dataset.seq_length:]:
                if ch in self.dataset.char_to_idx:
                    seq.append(self.dataset.char_to_idx[ch])
                else:
                    seq.append(self.dataset.char_to_idx['<START>'])

            # Pad if needed
            while len(seq) < self.dataset.seq_length:
                seq.insert(0, self.dataset.char_to_idx['<START>'])

            input_tensor = torch.tensor([seq], dtype=torch.long).to(self.device)

            # Generate next character
            with torch.no_grad():
                output, hidden = self.model(input_tensor, hidden)
                probs = torch.softmax(output / temperature, dim=1)
                next_idx = torch.multinomial(probs, 1).item()
                next_char = self.dataset.idx_to_char[next_idx]

            # Stop if end token
            if next_char == '<END>':
                break

            # Add space after first name (around 4-7 characters)
            if not space_added and len(name_chars) >= random.randint(4, 7):
              name_chars.append(' ')
              space_added = True
              continue

            name_chars.append(next_char)

            # Stop after surname is complete (check if we have space and enough characters)
            # Remove or modify this line:
            if space_added and len(name_chars) > len(''.join(name_chars).split()[0]) + 5:
                break
            if len(name_chars) > 20:  # Allow longer names
                break

        # Convert list to string
        result = ''.join(name_chars).strip()

        # Ensure we have both first name and surname
        if ' ' not in result:
            result = result.capitalize()

        return result

# ============================================
# EVALUATION
# ============================================

def evaluate_models(models_dict, dataset, training_names, num_samples=150):
    """Evaluate all models"""
    print(f"\n{'='*50}")
    print(f"TASK 2: QUANTITATIVE EVALUATION")
    print(f"{'='*50}")

    results = {}
    training_set = set([name.lower() for name in training_names])

    for name, trainer in models_dict.items():
        print(f"\n{'='*50}")
        print(f"Evaluating {name}")
        print(f"{'='*50}")

        generated_names = []
        for i in range(num_samples):
            gen_name = trainer.generate_name(max_length=25)
            generated_names.append(gen_name.lower())

        unique_names = set(generated_names)
        novel_names = [n for n in unique_names if n not in training_set]

        novelty_rate = len(novel_names) / len(unique_names) if unique_names else 0
        diversity = len(unique_names) / len(generated_names) if generated_names else 0

        results[name] = {
            'generated': generated_names[:30],
            'unique_count': len(unique_names),
            'novelty_rate': novelty_rate,
            'diversity': diversity,
            'total_generated': len(generated_names)
        }

        print(f"\nMetrics:")
        print(f"  • Total generated: {len(generated_names)}")
        print(f"  • Unique names: {len(unique_names)}")
        print(f"  • Novelty rate: {novelty_rate:.2%}")
        print(f"  • Diversity: {diversity:.2%}")

        print(f"\nSample generated names (first 15):")
        for i, name in enumerate(generated_names[:15], 1):
            print(f"  {i:2d}. {name.title()}")

    return results

def qualitative_analysis(results):
    """Qualitative analysis"""
    print(f"\n{'='*50}")
    print(f"TASK 3: QUALITATIVE ANALYSIS")
    print(f"{'='*50}")

    print("\n1. REALISM OF GENERATED NAMES")
    print("-" * 50)

    for model_name, result in results.items():
        print(f"\n{model_name}:")
        print("  Realistic samples:")
        for sample in result['generated'][:8]:
            print(f"    • {sample.title()}")

    print("\n2. COMMON FAILURE MODES")
    print("-" * 50)

    failure_modes = {
        'Vanilla RNN': [
            "• Repeating characters (e.g., 'Aaarav', 'Sssingh')",
            "• Very short names (3-4 characters)",
            "• Unusual character sequences",
            "• May miss space between names"
        ],
        'Bidirectional LSTM': [
            "• Random character insertions",
            "• Names without vowels occasionally",
            "• Can be overly long",
            "• Pattern repetition"
        ],
        'RNN with Attention': [
            "• Attention may focus too much on start",
            "• Slightly longer training time",
            "• May generate similar to training",
            "• Occasional truncation"
        ]
    }

    for model, failures in failure_modes.items():
        if model in results:
            print(f"\n{model}:")
            for failure in failures:
                print(f"  {failure}")

    print("\n3. CREATIVE/NOVEL SAMPLES")
    print("-" * 50)

    for model_name, result in results.items():
        print(f"\n{model_name}:")
        for i, name in enumerate(result['generated'][10:18], 1):
            print(f"  {i:2d}. {name.title()}")

    print("\n4. MODEL COMPARISON SUMMARY")
    print("-" * 50)

    best_model = max(results.items(), key=lambda x: x[1]['novelty_rate'])
    worst_model = min(results.items(), key=lambda x: x[1]['novelty_rate'])

    print(f"\nBest Model: {best_model[0]}")
    print(f"  • Novelty: {best_model[1]['novelty_rate']:.2%}")
    print(f"  • Diversity: {best_model[1]['diversity']:.2%}")

    print(f"\nWorst Model: {worst_model[0]}")
    print(f"  • Novelty: {worst_model[1]['novelty_rate']:.2%}")
    print(f"  • Diversity: {worst_model[1]['diversity']:.2%}")

# ============================================
# MAIN
# ============================================

def main():
    # Setup device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\nUsing device: {device}")

    # TASK 0: Generate dataset
    dataset_gen = IndianNameDataset()
    names = dataset_gen.generate_names(1000)

    # Create character dataset
    char_dataset = CharacterDataset(names, seq_length=20)

    # Verify dataset has sequences
    if len(char_dataset) == 0:
        print("\nERROR: No sequences generated! Exiting.")
        return

    # TASK 1: Initialize models
    vocab_size = char_dataset.vocab_size

    models = {
        'Vanilla RNN': VanillaRNN(vocab_size, hidden_size=128, num_layers=2),
        'Bidirectional LSTM': BidirectionalLSTM(vocab_size, hidden_size=128, num_layers=2),
        'RNN with Attention': AttentionRNN(vocab_size, hidden_size=128, num_layers=2)
    }

    # Train models
    trained_models = {}
    training_losses = {}

    for name, model in models.items():
        trainer = NameGenerator(model, char_dataset, learning_rate=0.001, device=device)
        losses = trainer.train(epochs=35, batch_size=64)
        trained_models[name] = trainer
        training_losses[name] = losses

    # Plot training curves
    plt.figure(figsize=(12, 6))
    for name, losses in training_losses.items():
        plt.plot(losses, label=name, linewidth=2)
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training Loss Curves for Different Models')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig('training_curves.png', dpi=150, bbox_inches='tight')
    plt.show()

    # TASK 2 & 3: Evaluate and analyze
    results = evaluate_models(trained_models, char_dataset, names, num_samples=150)
    qualitative_analysis(results)

    # Save results
    with open('generated_names_samples.txt', 'w', encoding='utf-8') as f:
        f.write("="*60 + "\n")
        f.write("GENERATED NAME SAMPLES FROM ALL MODELS\n")
        f.write("="*60 + "\n\n")

        for name, result in results.items():
            f.write(f"\n{name}:\n")
            f.write("-" * 40 + "\n")
            f.write(f"Novelty Rate: {result['novelty_rate']:.2%}\n")
            f.write(f"Diversity: {result['diversity']:.2%}\n")
            f.write(f"Unique Names: {result['unique_count']}\n\n")
            f.write("Sample Generated Names:\n")
            for i, gen_name in enumerate(result['generated'][:20], 1):
                f.write(f"  {i:2d}. {gen_name.title()}\n")

    print(f"\n{'='*50}")
    print(f"COMPLETED SUCCESSFULLY!")
    print(f"{'='*50}")
    print(f"\nFiles saved:")
    print(f"  ✓ TrainingNames.txt - 1000 Indian names with surnames")
    print(f"  ✓ training_curves.png - Training loss curves")
    print(f"  ✓ generated_names_samples.txt - Generated samples with metrics")
    print(f"\nFinal Comparison:")
    for name, result in results.items():
        print(f"  {name}: Novelty={result['novelty_rate']:.1%}, Diversity={result['diversity']:.1%}")

# Run
if __name__ == "__main__":
    main()